# Generated by Django 3.2 on 2022-10-13 20:47

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='Category', variations={'thumb': {'crop': True, 'height': 250, 'width': 250}}, verbose_name='Imagem')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='Offer', variations={'thumb': {'crop': True, 'height': 681, 'width': 423}}, verbose_name='Imagem')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(max_length=300, verbose_name='Descrição')),
                ('discount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('price', models.IntegerField()),
                ('image1', stdimage.models.StdImageField(force_min_size=False, upload_to='Product', variations={'thumb': {'crop': True, 'height': 597, 'width': 460}}, verbose_name='01. Imagem')),
                ('image2', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Product', variations={'thumb': {'crop': True, 'height': 597, 'width': 460}}, verbose_name='02. Imagem')),
                ('image3', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Product', variations={'thumb': {'crop': True, 'height': 557, 'width': 460}}, verbose_name='03. Imagem')),
                ('image4', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Product', variations={'thumb': {'crop': True, 'height': 597, 'width': 460}}, verbose_name='04. Imagem')),
                ('image5', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Product', variations={'thumb': {'crop': True, 'height': 597, 'width': 460}}, verbose_name='05. Imagem')),
                ('stock', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
